SO1/SO1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^supportOffice/', include('supportOffice.urls')),
]

SO1/supportOffice/urls.py
from django.conf.urls import url
from . import views
app_name ='supportOffice'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^Add PPMP/$', views.addPpmp, name='addPpmp'),
    url(r'^createPPMP$', views.createPPMP, name='createPPMP'),
    url(r'^PPMP List$', views.ppmpList, name='ppmpList'),
    url(r'^PPMP Details/(?P<id>\d+)$', views.ppmpDetailsAdd, name='ppmpDetailsAdd'),
    url(r'^addPPMPDetails/$', views.addPPMPDetails, name='addPPMPDetails'),
    url(r'^Generate PPMP/$', views.ppmpDetailsList, name='ppmpDetailsList'),
    url(r'^Generated PPMP/(?P<id>\d+)$', views.generatedPPMP, name='generatedPPMP'),
    url(r'^Recording In Document/(?P<id>\d+)$', views.viewDocument, name='viewDocument'),
    url(r'^Document List/$', views.listOfDocuments, name='listOfDocuments'),
    url(r'^monitorDoc$', views.monitorDoc, name='monitorDoc'),
    url(r'^monitorDocIn$', views.monitorDocIn, name='monitorDocIn'),
    url(r'^listOfRecordIn$', views.listOfRecordIn, name='listOfRecordIn'),

    # url(r'^sample3/$', views.sample3, name='sample3'),
    # url(r'^api_view/$', views.api_view, name='api_view'),
    # url(r'^time_in/$', views.time_in, name='time_in'),
    

    # url(r'^post/$', views.post, name='post'),

    #API URLS-FOR PPMP AND DOC MON
    url(r'category/', views.category),
    url(r'unit/', views.unit),
    url(r'item/', views.item),
    # url(r'ppmpDetails/', views.ppmpDetails),
    url(r'ItemSearch/', views.CategoryTin.as_view()),
    url(r'^doc/list/$', views.DocumentList.as_view()),
    url(r'^doc/add/$', views.DocumentAdd.as_view()),
    url(r'^doc/search$', views.DocumentSearch.as_view()),
    url(r'^documentMonitoring/$', views.documentMonitoring.as_view()),
    url(r'^docMonitoring/list/$', views.Doc_MonitoringList.as_view()),
    url(r'^docMonitoring/listDetails/$', views.Doc_MonitoringListDetails.as_view()),
    url(r'^docMonitoring/add/$', views.Doc_MonitoringAdd.as_view()),
    url(r'^docMonitoring/edit/$', views.Doc_MonitoringEdit.as_view()),
    url(r'^docMonitoring/search$', views.Doc_MonitoringSearch.as_view()),
    url(r'^ppmp/$', views.ppmp.as_view()),
    url(r'^ppmp/list/$', views.PPMPList.as_view()),
    url(r'^ppmp/listDetails/$', views.PPMPListDetails.as_view()),
    url(r'^ppmp/add/$', views.PPMPAdd.as_view()),
    url(r'^ppmp/edit/$', views.PPMPEdit.as_view()),
    url(r'^ppmpDetails/$', views.ppmpDetails.as_view()),
    url(r'^ppmpDetails/list/$', views.PPMP_DetailsList.as_view()),
    url(r'^ppmpDetails/listDetails/$', views.PPMP_DetailsListDetails.as_view()),
    url(r'^ppmpDetails/add/$', views.PPMP_DetailsAdd.as_view()),
    url(r'^ppmpDetails/edit/$', views.PPMP_DetailsEdit.as_view()),
]

SO1/supportOffice/views.py
#KANG CHRISTINE NGA MGA IMPORTS
from django.shortcuts import get_object_or_404

from django.db.models import Q
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, DestroyAPIView, UpdateAPIView, ListAPIView, RetrieveAPIView
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from django.http import JsonResponse
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from django.template import loader
from django.template.loader import render_to_string
from rest_framework import parsers, renderers, generics, status
from rest_framework import mixins
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.serializers import AuthTokenSerializer

# from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser, IsAuthenticatedOrReadOnly
# from rest_framework.authentication import TokenAuthentication

from rest_framework.renderers import TemplateHTMLRenderer
from .models import Category, Unit, Item, Document, Doc_Monitoring, PPMP, PPMP_Details, AccSection
from .serializers import CategorySerializer, UnitSerializer, Item_GETSerializer, ItemSerializer, DocumentListSerializer, DocumentAddSerializer, DocumentEditSerializer, Doc_MonitoringListSerializer, Doc_MonitoringAddSerializer, Doc_MonitoringEditSerializer, PPMPListSerializer, PPMPListSerializer1, PPMPAddSerializer, PPMPEditSerializer, PPMP_DetailsListSerializer, PPMP_DetailsAddSerializer, PPMP_DetailsEditSerializer
from supportOffice import serializers
#DIRI TAMAN
from django.shortcuts import render, redirect, HttpResponse
from django import template
from django.conf.urls import url
import requests, json
import datetime
from datetime import datetime, timezone
from time import gmtime, strftime
# def getHostNameInfo():
#     now = datetime.now()
#     print(now.strftime("%A, %B %d, %Y, %I:%M:%S%p"))
# getHostNameInfo()
def index(request):
    return render(request, 'supportOffice/index.html',)

def home(request):
    return render(request, 'supportOffice/home.html',)

def addPpmp(request):
    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/')
    addPpmp=json.loads(req.content.decode('UTF-8'))
    return render(request, 'supportOffice/addPpmp.html', {'addPpmp': addPpmp })

def createPPMP(request):

    data = {
        "ForTheYear":request.GET['ppmp_year'],
        "PpmpCode":request.GET['ppmp_code'],
        "PpmpType":request.GET['ppmp_type'],
        "PpmpCreatedBy":request.GET['createdBy']
    }


    temp=json.dumps(data)
    #return HttpResponse(temp, content_type="application/json; charset=UTF-8")
    req=requests.post('http://127.0.0.1:8000/supportOffice/ppmp/', temp, headers={'content-type':'application/json'} )
    return HttpResponse(req.content,content_type="application/json")
    #requests.post('http://127.0.0.1:8000/supportOffice/diagnosis/',temp2, headers={'content-type':'application/json'} )
    #return redirect('supportOffice:add_consultation')

def ppmpList(request):    

    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/')
    ppmpList=json.loads(req.content.decode('UTF-8'))
    return render(request, 'supportOffice/ppmpList.html', {'ppmpList': ppmpList})

def ppmpDetailsAdd(request, id):

    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/?id='+id)
    ppmp=json.loads(req.content.decode('UTF-8'))

    reqq=requests.get('http://127.0.0.1:8000/supportOffice/ppmpDetails/')
    ppmpDet=json.loads(reqq.content.decode('UTF-8'))

    reqqq=requests.get('http://127.0.0.1:8000/supportOffice/item/')
    item=json.loads(reqqq.content.decode('UTF-8'))
    return render(request, 'supportOffice/ppmpDetails.html', {'ppmp': ppmp, 'ppmpDet': ppmpDet, 'item': item})
    
def addPPMPDetails(request):

    data = {
        "PpmpID":request.GET['ppmpID'],
        "UnitPrice":request.GET['ppmpDetPrice'],
        "PpmpQuantity":request.GET['ppmpDetQty'],
        "Schedule":request.GET['ppmpDetSched'],
        "ItemID":request.GET['ppmpDetItem'],
        "EstimatedTotal":request.GET['ppmpEsTotal'],
    }

    temp=json.dumps(data)
    #return HttpResponse(temp, content_type="application/json; charset=UTF-8")
    req=requests.post('http://127.0.0.1:8000/supportOffice/ppmpDetails/', temp, headers={'content-type':'application/json'} )
    return HttpResponse(req.content,content_type="application/json")
    #requests.post('http://127.0.0.1:8000/supportOffice/diagnosis/',temp2, headers={'content-type':'application/json'} )
    #return redirect('supportOffice:add_consultation')

def ppmpDetailsList(request):

    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/')
    ppmpList=json.loads(req.content.decode('UTF-8'))
    return render(request, 'supportOffice/ppmpDetailsList.html', {'ppmpList': ppmpList})

def listOfDocuments(request):

    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/')
    ppmpList=json.loads(req.content.decode('UTF-8'))
    return render(request, 'supportOffice/listOfDocuments.html', {'ppmpList': ppmpList})

def generatedPPMP(request, id):

    reqq=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/?id='+id)
    ppmp=json.loads(reqq.content.decode('UTF-8'))

    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmpDetails/?id='+id)
    ppmpList=json.loads(req.content.decode('UTF-8'))

    return render(request, 'supportOffice/generatedPPMP.html', {'ppmpList': ppmpList, 'ppmp': ppmp})

def viewDocument(request, id):

    reqq=requests.get('http://127.0.0.1:8000/supportOffice/ppmp/?id='+id)
    ppmp=json.loads(reqq.content.decode('UTF-8'))

    req=requests.get('http://127.0.0.1:8000/supportOffice/ppmpDetails/?id='+id)
    ppmpList=json.loads(req.content.decode('UTF-8'))

    return render(request, 'supportOffice/viewDocument.html', {'ppmpList': ppmpList, 'ppmp': ppmp})

def monitorDoc(request):

    data = {
        "PpmpID": request.GET['ppmp_id'],
        "In_Out":request.GET['document_in_out'],
        "DocumentStatus": request.GET['document_status'],
        "DocumentRemarks":request.GET['document_remarks'],
        "MonitoredBy":request.GET['monitored_by'],
    }

    temp=json.dumps(data)
    #return HttpResponse(temp, content_type="application/json; charset=UTF-8")
    req=requests.post('http://127.0.0.1:8000/supportOffice/documentMonitoring/',temp, headers={'content-type':'application/json'} )
    return HttpResponse(req.content,content_type="application/json")

def monitorDocIn(request):

    data = {
        "PpmpID": request.GET['ppmp_id1'],
        "In_Out":request.GET['document_in_out1'],
        "DocumentStatus": request.GET['document_status1'],
        "DocumentRemarks":request.GET['document_remarks1'],
        "MonitoredBy":request.GET['monitored_by1'],
    }

    temp=json.dumps(data)
    #return HttpResponse(temp, content_type="application/json; charset=UTF-8")
    req=requests.post('http://127.0.0.1:8000/supportOffice/docMonitoring/add/',temp, headers={'content-type':'application/json'} )
    return HttpResponse(req.content,content_type="application/json")

def listOfRecordIn(request):

    reqq=requests.get('http://127.0.0.1:8000/supportOffice/docMonitoring/list/')
    ppmp=json.loads(reqq.content.decode('UTF-8'))

    return render(request, 'supportOffice/listOfRecordIn.html', {'ppmp': ppmp})


# Use to access api Search bar RECORD OUT
# def sample3(request):
#     req = requests.get('http://127.0.0.1:8000/supportOffice/docMonitoring/search?q=' + request.GET['query'])
#     return HttpResponse(req.content, content_type = "application/json; charset=UTF-8")

# def api_view(request):
#     req = requests.get('http://127.0.0.1:8000/supportOffice/ppmpDetails/listDetails/?id=' + request.GET['query'])
#     return HttpResponse(req.content, content_type = "application/json; charset=UTF-8")

# def time_in(request):
#     req = requests.get('http://127.0.0.1:8000/supportOffice/ppmpDetails/listDetails/?id=' + request.GET['query'])
#     return HttpResponse(req.content, content_type = "application/json; charset=UTF-8")


# def post(self, request, format=None):
#     time = request.data['time']
#     section = request.data['section']


#     if not time and not section:
#         raise Http404
#     else:
#         designation = designation.objects.get(name=name)
#         designation = designation.objects.get(time=time)
#         designation.name=name
#         designation.time=time
#         designation.save()

   # req = requests.get('http://127.0.0.1:8000/supportOffice/docMonitoring/search?q=' + request.GET['query'])

#    now = datetime.now()
#     print(now.strftime("%A, %B %d, %Y, %I:%M:%S%p")
#     api_record_in()
#    return HttpResponse(req.content, content_type = "application/json; charset=UTF-8")


# KANG CHRISTINE NGA MGA VIEWS
@csrf_exempt
@api_view(['GET', 'POST', 'PUT', 'DELETE'])
def category(request):
    if request.method == 'GET':
        if 'id' in request.GET:
            id = request.GET['id']
            category = Category.objects.get(pk=id)
            serializer = CategorySerializer(category)
            return JsonResponse(serializer.data, safe = False)
        elif 'Description' in request.GET:
            Description = request.GET['Description']
            category = Category.objects.filter(Description__icontains = Description)
            serializer = CategorySerializer(category, many = True)
            return JsonResponse(serializer.data, safe = False)
        else:
            category = Category.objects.all()
            serializer = CategorySerializer(category, many = True)
            return JsonResponse(serializer.data, safe = False)

    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = CategorySerializer(data=data)

SO1/supportOffice/templates/supportOffice/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <title>PPMP and Document Monitoring System</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'supportOffice/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="{% static 'supportOffice/css/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{% static 'supportOffice/css/dataTables/dataTables.bootstrap.css' %}" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="{% static 'supportOffice/css/dataTables/dataTables.bootstrap.css" rel="stylesheet' %}">
    <link href="{% static 'supportOffice/css/dataTables/dataTables.responsive.css' %}" rel="stylesheet">
    <!-- Timeline CSS -->
    <link href="{% static 'supportOffice/css/timeline.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'supportOffice/css/startmin.css' %}" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="{% static 'supportOffice/css/morris.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'supportOffice/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'supportOffice/js/jquery.min.js' %}"></script>
    <script src="{% static 'supportOffice/js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'supportOffice/js/jquery-3.2.1.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'supportOffice/images/msunlogo.png' %}">
</head>

<body>


    <div id="page-wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'supportOffice:index' %}">MSU NAAWAN</a>

                </div>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                  <ul class="nav navbar-right navbar-top-links">
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> Admin <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            
                             <li>
                                <a href="{% url 'supportOffice:index' %}"><i class="fa fa-dashboard"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-file"></i> PPMP<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'supportOffice:addPpmp' %}"><i class="fa fa-plus"></i> Create PPMP</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'supportOffice:ppmpList' %}"><i class="fa fa-list-ol"></i> List of Created PPMP</a>
                                    </li> 
                                    <li>
                                        <a href="{% url 'supportOffice:ppmpDetailsList' %}"><i class="fa fa-list-ol"></i> Generate PPMP Report</a>
                                    </li>
                                    
                                    
                                   
                                </ul>
                            </li>
                            
                            <li>
                                <a href="#"><i class="fa fa-eye"></i> Monitor Documents<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'supportOffice:listOfDocuments' %}"><i class="fa fa-list-ol"></i> View Documents</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'supportOffice:listOfRecordIn' %}"><i class="fa fa-list-ol"></i> View Logs</a>
                                    </li>                                
                                    
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="#"><i class="fa  fa-sign-out "></i> Sign out</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div class="row">
            {% block header%}
            {% endblock %}
        </div>

       <div>
           <br>
       </div>
         <div class="row">
            
            {% block content %}
            
             {% endblock %}
               

        </div>
       
     <div class="row">
    
    </div>
    </div>
    {% block body %} {% endblock %}
    
</body>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'supportOffice/js/bootstrap.min.js' %}"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'supportOffice/js/metisMenu.min.js' %}"></script>
<!-- Morris Charts JavaScript -->
<script src="{% static 'supportOffice/js/raphael.min.js' %}"></script>
<script src="{% static 'supportOffice/js/dataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'supportOffice/js/dataTables/dataTables.bootstrap.min.js' %}"></script>
<!-- Custom Theme JavaScript -->
<script src="{% static 'supportOffice/js/startmin.js' %}"></script>
<!-- <script src="{% static 'supportOffice/js/dc.js' %}"></script> -->
</html>

SO1/supportOffice/templates/supportOffice/index.html
{% extends 'supportOffice/base.html' %}
{% block header %}
<div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
{% endblock %}
{% block content %}

{% endblock %}

SO1/supportOffice/templates/supportOffice/viewDocument.html
{%extends 'supportOffice/base.html' %}
{% block header %}
<div class="col-lg-12">
        <h1 class="page-header">Generated PPMP</h1>
        
    </div>
{% endblock %}
{% block content %}
<div>
    <h3>ID: {{ ppmp.id }}</h3>
                 <h3>Cost Center: {{ ppmp.PpmpCreatedBy.section.name }} - {{ ppmp.PpmpCreatedBy.section.department.name }} For the Year( {{ ppmp.ForTheYear }} )</h3>
</div>
<div class="col-md-12 col-md-offset-9">
  <button href="#modalLoad1" data-toggle="modal" class="btn btn-primary"> <i class="fa fa-arrow-down"></i> Record In</button>
  <button  href="#modalLoad"  data-toggle="modal" class="btn btn-warning"><i class="fa fa-arrow-up"></i> <b>Record Out</b></button>
  <br>
</div>
<br>

<div class="col-lg-12">
  <br>
    <div class="panel panel-default">
        <div class="panel-heading">
                               Documents
                            </div>
      <div class="panel-body">

        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped  table-bordered table-hover table-responsive" id="dataTables">
                    <thead>
                        <tr>
                                    <th style="width:15%">Document ID</th>
                                    <th>Category</th>
                                    <th>Item</th>
                                     <th>Unit Price</th>
                            <th>Quantity</th>
                            <th>Schedule</th>
                                    <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                                {% for PPMP_Details in ppmpList %}
                        <tr>
                                    <td>{{ PPMP_Details.PpmpID.id }}</td>
                                    <td>{{ PPMP_Details.ItemID.CategoryID.Description }}</td>
                                    <td>{{ PPMP_Details.ItemID.Name }}</td>
                                    <td>{{ PPMP_Details.UnitPrice }}</td>
                            <td>{{ PPMP_Details.PpmpQuantity }}</td>
                            <td>{{ PPMP_Details.Schedule }}</td>
                                    <td>{{ PPMP_Details.EstimatedTotal }}</td>
                           
                        </tr>
                               {% endfor %}
                    </tbody>
                </table>
              </br>             
            </div>
        </div>

      </div>
    </div>

<div class="modal fade" id="modalLoad" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
      <div class="modal-content ">
          <form id="load">
              <div class="modal-header">
                  <h2 class="modal-title"><b>Record Out</b></h2>
              </div>
              
              <div class="modal-body">
                <div class="container-fluid">
                  <div class='col-md-6'>
                      <div class='form-group fg-line'>
                        <label>Document No.</label>
                        <input class="form-control" type="text" name="ppmp_id" id="ppmp_id" value="{{ ppmp.id }}" disabled>
                      </div>
                  </div>
                  <div class='col-md-6'>
                      <input type="hidden" name="document_in_out" id="document_in_out" value="OUT">
                  </div>
                  <div class='col-md-6'>
                      <input type="hidden" name="document_status" id="document_status" value="REJECTED">
                  </div>
                  <div class='col-md-6'>
                      <div class='form-group fg-line'>
                        <label>Document's Remarks</label>
                          <input class="form-control" type="text" name="document_remarks" id="document_remarks" placeholder="Remarks">
                      </div>
                  </div>
                  <div class='col-md-6'>
                      <div class='form-group fg-line'>
                        <input type="hidden" name="monitored_by" id="monitored_by" value="1">
                      </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <input type="hidden" name="ppmp_id" id="ppmp_id" value="{{ ppmp.id }}">
                  <button type="submit" id="insert1" class="btn btn-warning">RECORD OUT</button>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">CANCEL
                  </button>
              </div>
          </form>
          <script>
            $(document).ready(function(){
              $("#load").submit(function(){
                $.ajax({
                  type: "GET",
                  data: $("#load").serialize(),
                  url: '{% url 'supportOffice:monitorDoc' %}',
                  dataType: 'json',
                  success: function(data)
                  {
                    var arr = JSON.parse(JSON.stringify(data));
                    alert(JSON.stringify(arr));
                    alert('Succesfully added!');
                  },
                  error: function()
                  {
                    alert('The document has been record out.');
                    window.location="{% url 'supportOffice:listOfDocuments' %}";
                  }
                });
              });
            });
          </script>
      </div>
  </div>
</div>
<div class="modal fade" id="modalLoad1" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
      <div class="modal-content ">
          <form id="load1">
              <div class="modal-header">
                  <h2 class="modal-title"><b>Record In</b></h2>
              </div>
              
              <div class="modal-body">
                <div class="container-fluid">
                  <div class='col-md-6'>
                      <div class='form-group fg-line'>
                        <label>Document No.</label>
                        <input class="form-control" type="text" name="ppmp_id1" id="ppmp_id1" value="{{ ppmp.id }}" disabled>
                      </div>
                  </div>
                  <div class='col-md-6'>
                    <div class='form-group fg-line'>
                        <label>Type</label>
                      <input class="form-control" type="text" name="document_in_out1" id="document_in_out1" value="IN" disabled>
                    </div>
                  </div>
                  <div class='col-md-6'>
                    <div class='form-group fg-line'>
                        <label>Document Status</label>
                      <input class="form-control" type="text" name="document_status1" id="document_status1" value="PENDING" disabled>
                    </div>
                  </div>
                  <div class='col-md-6'>
                      <div class='form-group fg-line'>
                        <label>Document's Remarks</label>
                          <input class="form-control" type="text" name="document_remarks1" id="document_remarks1" placeholder="Remarks">
                      </div>
                  </div>
                  <div class='col-md-6'>
                      <div class='form-group fg-line'>
                        <label>Monitored By</label>
                        <input class="form-control" type="text" name="monitored_by1" id="monitored_by1" value="1" disabled>
                      </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <input type="hidden" name="ppmp_id" id="ppmp_id" value="{{ ppmp.id }}">
                <input type="hidden" name="document_in_out1" id="document_in_out1" value="IN">
                <input type="hidden" name="document_status1" id="document_status1" value="APPROVED">
                <input type="hidden" name="monitored_by1" id="monitored_by1" value="1">
                  <button type="submit" id="insert" class="btn btn-success">RECORD IN</button>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">CANCEL
                  </button>
              </div>
          </form>
          <script>
            $(document).ready(function(){
              $("#load1").submit(function(){
                $.ajax({
                  type: "GET",
                  data: $("#load1").serialize(),
                  url: '{% url 'supportOffice:monitorDocIn' %}',
                  dataType: 'json',
                  success: function(data)
                  {
                    alert('Document has been record in.');
                  },
                  error: function()
                  {
                    alert('The document has been record in.');
                    window.location="{% url 'supportOffice:listOfRecordIn' %}";
                  }
                });
              });
            });
          </script>
      </div>
  </div>
</div>
{% endblock %}